<?xml version="1.0" encoding="utf-8"?><Database Name="DB_PLANT_PPE_NEW_KPT" Class="DB_Plant_PPEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=kphosq101\shpol;Initial Catalog=DB_PLANT_PPE_NEW_KPT;User ID=sqlservices" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_PLANT_PPE_NEW_KPTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_M_AKSES" Member="TBL_M_AKSEs">
    <Type Name="TBL_M_AKSE">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IS_ALLOW" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_USER" Member="TBL_M_USERs">
    <Type Name="TBL_M_USER">
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_ROLE" Member="TBL_M_ROLEs">
    <Type Name="TBL_M_ROLE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_R_MENU" Member="TBL_R_MENUs">
    <Type Name="TBL_R_MENU">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sub_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icon_Menu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link_Menu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Akses" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_R_SUB_MENU" Member="TBL_R_SUB_MENUs">
    <Type Name="TBL_R_SUB_MENU">
      <Column Name="ID_Sub_Menu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sub_Menu_Description" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link_Sub_Menu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Akses" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_ALL" Member="VW_KARYAWAN_ALLs">
    <Type Name="VW_KARYAWAN_ALL">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_M_AKSES" Member="VW_M_AKSEs">
    <Type Name="VW_M_AKSE">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_MENU" Member="VW_MENUs">
    <Type Name="VW_MENU">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="IS_ALLOW" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_MENU" Member="VW_R_MENUs">
    <Type Name="VW_R_MENU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sub_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icon_Menu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link_Menu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_User" Member="VW_Users">
    <Type Name="VW_User">
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_M_JOBSITE" Member="VW_M_JOBSITEs">
    <Type Name="VW_M_JOBSITE">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_MSF020" Member="VW_MSF020s">
    <Type Name="VW_MSF020">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="ENTITY" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ENTRY_TYPE" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CREATION_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="DEFAULT_FLAG" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DEFAULT_MENU" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="GLOBAL_PROFILE" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_ACC_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_TIME" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_USER" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_NO_ERR_LOGS" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="OGUI_GLOBAL_PROF" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="OWNER_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="PASS_WORD" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="PROFILE" Type="System.String" DbType="Char(250) NOT NULL" CanBeNull="false" />
      <Column Name="PROFILE_LOGIN_LCKD" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="PSW_UPD_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="RECENT_PWD_GRP" Type="System.String" DbType="Char(204) NOT NULL" CanBeNull="false" />
      <Column Name="SECURITY_ACCESS" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_EMP" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>