#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_PLANT_PPE.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PLANT_PPE_NEW_KPT")]
	public partial class DB_Plant_PPEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_AKSE(TBL_M_AKSE instance);
    partial void UpdateTBL_M_AKSE(TBL_M_AKSE instance);
    partial void DeleteTBL_M_AKSE(TBL_M_AKSE instance);
    partial void InsertTBL_M_USER(TBL_M_USER instance);
    partial void UpdateTBL_M_USER(TBL_M_USER instance);
    partial void DeleteTBL_M_USER(TBL_M_USER instance);
    partial void InsertTBL_M_ROLE(TBL_M_ROLE instance);
    partial void UpdateTBL_M_ROLE(TBL_M_ROLE instance);
    partial void DeleteTBL_M_ROLE(TBL_M_ROLE instance);
    partial void InsertTBL_R_MENU(TBL_R_MENU instance);
    partial void UpdateTBL_R_MENU(TBL_R_MENU instance);
    partial void DeleteTBL_R_MENU(TBL_R_MENU instance);
    partial void InsertTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void UpdateTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void DeleteTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void InsertTBL_M_AGREEMENT(TBL_M_AGREEMENT instance);
    partial void UpdateTBL_M_AGREEMENT(TBL_M_AGREEMENT instance);
    partial void DeleteTBL_M_AGREEMENT(TBL_M_AGREEMENT instance);
    partial void InsertTBL_M_DISTRICT(TBL_M_DISTRICT instance);
    partial void UpdateTBL_M_DISTRICT(TBL_M_DISTRICT instance);
    partial void DeleteTBL_M_DISTRICT(TBL_M_DISTRICT instance);
    partial void InsertTBL_M_MAPPING_APPROVAL(TBL_M_MAPPING_APPROVAL instance);
    partial void UpdateTBL_M_MAPPING_APPROVAL(TBL_M_MAPPING_APPROVAL instance);
    partial void DeleteTBL_M_MAPPING_APPROVAL(TBL_M_MAPPING_APPROVAL instance);
    #endregion
		
		public DB_Plant_PPEDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_PLANT_PPE_NEW_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Plant_PPEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Plant_PPEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Plant_PPEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Plant_PPEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_AKSE> TBL_M_AKSEs
		{
			get
			{
				return this.GetTable<TBL_M_AKSE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_USER> TBL_M_USERs
		{
			get
			{
				return this.GetTable<TBL_M_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_ROLE> TBL_M_ROLEs
		{
			get
			{
				return this.GetTable<TBL_M_ROLE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MENU> TBL_R_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_SUB_MENU> TBL_R_SUB_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_SUB_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_KARYAWAN_ALL> VW_KARYAWAN_ALLs
		{
			get
			{
				return this.GetTable<VW_KARYAWAN_ALL>();
			}
		}
		
		public System.Data.Linq.Table<VW_M_AKSE> VW_M_AKSEs
		{
			get
			{
				return this.GetTable<VW_M_AKSE>();
			}
		}
		
		public System.Data.Linq.Table<VW_MENU> VW_MENUs
		{
			get
			{
				return this.GetTable<VW_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_MENU> VW_R_MENUs
		{
			get
			{
				return this.GetTable<VW_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_User> VW_Users
		{
			get
			{
				return this.GetTable<VW_User>();
			}
		}
		
		public System.Data.Linq.Table<VW_M_JOBSITE> VW_M_JOBSITEs
		{
			get
			{
				return this.GetTable<VW_M_JOBSITE>();
			}
		}
		
		public System.Data.Linq.Table<VW_MSF020> VW_MSF020s
		{
			get
			{
				return this.GetTable<VW_MSF020>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_AGREEMENT> TBL_M_AGREEMENTs
		{
			get
			{
				return this.GetTable<TBL_M_AGREEMENT>();
			}
		}
		
		public System.Data.Linq.Table<VW_DISTRICT> VW_DISTRICTs
		{
			get
			{
				return this.GetTable<VW_DISTRICT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_DISTRICT> TBL_M_DISTRICTs
		{
			get
			{
				return this.GetTable<TBL_M_DISTRICT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_POSITION> TBL_M_POSITIONs
		{
			get
			{
				return this.GetTable<TBL_M_POSITION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_MAPPING_APPROVAL> TBL_M_MAPPING_APPROVALs
		{
			get
			{
				return this.GetTable<TBL_M_MAPPING_APPROVAL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_AKSES")]
	public partial class TBL_M_AKSE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private int _ID_Role;
		
		private System.Nullable<bool> _IS_ALLOW;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnID_RoleChanging(int value);
    partial void OnID_RoleChanged();
    partial void OnIS_ALLOWChanging(System.Nullable<bool> value);
    partial void OnIS_ALLOWChanged();
    #endregion
		
		public TBL_M_AKSE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ALLOW", DbType="Bit")]
		public System.Nullable<bool> IS_ALLOW
		{
			get
			{
				return this._IS_ALLOW;
			}
			set
			{
				if ((this._IS_ALLOW != value))
				{
					this.OnIS_ALLOWChanging(value);
					this.SendPropertyChanging();
					this._IS_ALLOW = value;
					this.SendPropertyChanged("IS_ALLOW");
					this.OnIS_ALLOWChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_USER")]
	public partial class TBL_M_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Role;
		
		private string _Username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RoleChanging(int value);
    partial void OnID_RoleChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public TBL_M_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_ROLE")]
	public partial class TBL_M_ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RoleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public TBL_M_ROLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MENU")]
	public partial class TBL_R_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MenuChanging(int value);
    partial void OnID_MenuChanged();
    partial void OnName_MenuChanging(string value);
    partial void OnName_MenuChanged();
    partial void OnSub_MenuChanging(System.Nullable<int> value);
    partial void OnSub_MenuChanged();
    partial void OnIcon_MenuChanging(string value);
    partial void OnIcon_MenuChanged();
    partial void OnLink_MenuChanging(string value);
    partial void OnLink_MenuChanged();
    partial void OnOrderChanging(System.Nullable<int> value);
    partial void OnOrderChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this.OnName_MenuChanging(value);
					this.SendPropertyChanging();
					this._Name_Menu = value;
					this.SendPropertyChanged("Name_Menu");
					this.OnName_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this.OnSub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu = value;
					this.SendPropertyChanged("Sub_Menu");
					this.OnSub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this.OnIcon_MenuChanging(value);
					this.SendPropertyChanging();
					this._Icon_Menu = value;
					this.SendPropertyChanged("Icon_Menu");
					this.OnIcon_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this.OnLink_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Menu = value;
					this.SendPropertyChanged("Link_Menu");
					this.OnLink_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this.OnOrderChanging(value);
					this.SendPropertyChanging();
					this._Order = value;
					this.SendPropertyChanged("Order");
					this.OnOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_SUB_MENU")]
	public partial class TBL_R_SUB_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Sub_Menu;
		
		private System.Nullable<int> _ID_Menu;
		
		private string _Sub_Menu_Description;
		
		private string _Link_Sub_Menu;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Sub_MenuChanging(int value);
    partial void OnID_Sub_MenuChanged();
    partial void OnID_MenuChanging(System.Nullable<int> value);
    partial void OnID_MenuChanged();
    partial void OnSub_Menu_DescriptionChanging(string value);
    partial void OnSub_Menu_DescriptionChanged();
    partial void OnLink_Sub_MenuChanging(string value);
    partial void OnLink_Sub_MenuChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_SUB_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sub_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Sub_Menu
		{
			get
			{
				return this._ID_Sub_Menu;
			}
			set
			{
				if ((this._ID_Sub_Menu != value))
				{
					this.OnID_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Sub_Menu = value;
					this.SendPropertyChanged("ID_Sub_Menu");
					this.OnID_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int")]
		public System.Nullable<int> ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu_Description", DbType="NVarChar(150)")]
		public string Sub_Menu_Description
		{
			get
			{
				return this._Sub_Menu_Description;
			}
			set
			{
				if ((this._Sub_Menu_Description != value))
				{
					this.OnSub_Menu_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu_Description = value;
					this.SendPropertyChanged("Sub_Menu_Description");
					this.OnSub_Menu_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Sub_Menu", DbType="NVarChar(250)")]
		public string Link_Sub_Menu
		{
			get
			{
				return this._Link_Sub_Menu;
			}
			set
			{
				if ((this._Link_Sub_Menu != value))
				{
					this.OnLink_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Sub_Menu = value;
					this.SendPropertyChanged("Link_Sub_Menu");
					this.OnLink_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KARYAWAN_ALL")]
	public partial class VW_KARYAWAN_ALL
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _EMP_STATUS;
		
		private string _GENDER_CODE;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _EMAIL;
		
		private string _ACTIVE_STATUS;
		
		public VW_KARYAWAN_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(100)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(100)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(100)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(100)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(100)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(100)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(100)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(100)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(100)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(100)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(100)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="VarChar(100)")]
		public string ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_M_AKSES")]
	public partial class VW_M_AKSE
	{
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private int _ID_Role;
		
		private string _RoleName;
		
		public VW_M_AKSE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this._Name_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL")]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this._ID_Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_MENU")]
	public partial class VW_MENU
	{
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private int _ID_Role;
		
		private string _RoleName;
		
		private System.Nullable<bool> _IS_ALLOW;
		
		public VW_MENU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this._Name_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL")]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this._ID_Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ALLOW", DbType="Bit")]
		public System.Nullable<bool> IS_ALLOW
		{
			get
			{
				return this._IS_ALLOW;
			}
			set
			{
				if ((this._IS_ALLOW != value))
				{
					this._IS_ALLOW = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_MENU")]
	public partial class VW_R_MENU
	{
		
		private int _ID;
		
		private string _RoleName;
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		public VW_R_MENU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this._Name_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this._Sub_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this._Icon_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this._Link_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this._Order = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_User")]
	public partial class VW_User
	{
		
		private int _ID_Role;
		
		private string _Username;
		
		private string _NAME;
		
		private string _EMAIL;
		
		private string _DSTRCT_CODE;
		
		private string _RoleName;
		
		public VW_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL")]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this._ID_Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_M_JOBSITE")]
	public partial class VW_M_JOBSITE
	{
		
		private string _DSTRCT_CODE;
		
		private string _CODE;
		
		public VW_M_JOBSITE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="Char(18) NOT NULL", CanBeNull=false)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_MSF020")]
	public partial class VW_MSF020
	{
		
		private string _DSTRCT_CODE;
		
		private string _ENTITY;
		
		private char _ENTRY_TYPE;
		
		private string _CREATION_DATE;
		
		private char _DEFAULT_FLAG;
		
		private string _DEFAULT_MENU;
		
		private string _EMPLOYEE_ID;
		
		private string _GLOBAL_PROFILE;
		
		private string _LAST_ACC_DATE;
		
		private string _LAST_MOD_DATE;
		
		private string _LAST_MOD_TIME;
		
		private string _LAST_MOD_USER;
		
		private string _LAST_NO_ERR_LOGS;
		
		private string _OGUI_GLOBAL_PROF;
		
		private string _OWNER_ID;
		
		private string _PASS_WORD;
		
		private string _PROFILE;
		
		private char _PROFILE_LOGIN_LCKD;
		
		private string _PSW_UPD_DATE;
		
		private string _RECENT_PWD_GRP;
		
		private char _SECURITY_ACCESS;
		
		private string _LAST_MOD_EMP;
		
		public VW_MSF020()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTITY", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ENTITY
		{
			get
			{
				return this._ENTITY;
			}
			set
			{
				if ((this._ENTITY != value))
				{
					this._ENTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_TYPE", DbType="Char(1) NOT NULL")]
		public char ENTRY_TYPE
		{
			get
			{
				return this._ENTRY_TYPE;
			}
			set
			{
				if ((this._ENTRY_TYPE != value))
				{
					this._ENTRY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this._CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEFAULT_FLAG", DbType="Char(1) NOT NULL")]
		public char DEFAULT_FLAG
		{
			get
			{
				return this._DEFAULT_FLAG;
			}
			set
			{
				if ((this._DEFAULT_FLAG != value))
				{
					this._DEFAULT_FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEFAULT_MENU", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string DEFAULT_MENU
		{
			get
			{
				return this._DEFAULT_MENU;
			}
			set
			{
				if ((this._DEFAULT_MENU != value))
				{
					this._DEFAULT_MENU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLOBAL_PROFILE", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string GLOBAL_PROFILE
		{
			get
			{
				return this._GLOBAL_PROFILE;
			}
			set
			{
				if ((this._GLOBAL_PROFILE != value))
				{
					this._GLOBAL_PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_ACC_DATE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string LAST_ACC_DATE
		{
			get
			{
				return this._LAST_ACC_DATE;
			}
			set
			{
				if ((this._LAST_ACC_DATE != value))
				{
					this._LAST_ACC_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_DATE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_DATE
		{
			get
			{
				return this._LAST_MOD_DATE;
			}
			set
			{
				if ((this._LAST_MOD_DATE != value))
				{
					this._LAST_MOD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_TIME", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_TIME
		{
			get
			{
				return this._LAST_MOD_TIME;
			}
			set
			{
				if ((this._LAST_MOD_TIME != value))
				{
					this._LAST_MOD_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_USER", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_USER
		{
			get
			{
				return this._LAST_MOD_USER;
			}
			set
			{
				if ((this._LAST_MOD_USER != value))
				{
					this._LAST_MOD_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NO_ERR_LOGS", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string LAST_NO_ERR_LOGS
		{
			get
			{
				return this._LAST_NO_ERR_LOGS;
			}
			set
			{
				if ((this._LAST_NO_ERR_LOGS != value))
				{
					this._LAST_NO_ERR_LOGS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OGUI_GLOBAL_PROF", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string OGUI_GLOBAL_PROF
		{
			get
			{
				return this._OGUI_GLOBAL_PROF;
			}
			set
			{
				if ((this._OGUI_GLOBAL_PROF != value))
				{
					this._OGUI_GLOBAL_PROF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OWNER_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string OWNER_ID
		{
			get
			{
				return this._OWNER_ID;
			}
			set
			{
				if ((this._OWNER_ID != value))
				{
					this._OWNER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS_WORD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string PASS_WORD
		{
			get
			{
				return this._PASS_WORD;
			}
			set
			{
				if ((this._PASS_WORD != value))
				{
					this._PASS_WORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE", DbType="Char(250) NOT NULL", CanBeNull=false)]
		public string PROFILE
		{
			get
			{
				return this._PROFILE;
			}
			set
			{
				if ((this._PROFILE != value))
				{
					this._PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE_LOGIN_LCKD", DbType="Char(1) NOT NULL")]
		public char PROFILE_LOGIN_LCKD
		{
			get
			{
				return this._PROFILE_LOGIN_LCKD;
			}
			set
			{
				if ((this._PROFILE_LOGIN_LCKD != value))
				{
					this._PROFILE_LOGIN_LCKD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSW_UPD_DATE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string PSW_UPD_DATE
		{
			get
			{
				return this._PSW_UPD_DATE;
			}
			set
			{
				if ((this._PSW_UPD_DATE != value))
				{
					this._PSW_UPD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECENT_PWD_GRP", DbType="Char(204) NOT NULL", CanBeNull=false)]
		public string RECENT_PWD_GRP
		{
			get
			{
				return this._RECENT_PWD_GRP;
			}
			set
			{
				if ((this._RECENT_PWD_GRP != value))
				{
					this._RECENT_PWD_GRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECURITY_ACCESS", DbType="Char(1) NOT NULL")]
		public char SECURITY_ACCESS
		{
			get
			{
				return this._SECURITY_ACCESS;
			}
			set
			{
				if ((this._SECURITY_ACCESS != value))
				{
					this._SECURITY_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_EMP", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_EMP
		{
			get
			{
				return this._LAST_MOD_EMP;
			}
			set
			{
				if ((this._LAST_MOD_EMP != value))
				{
					this._LAST_MOD_EMP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_AGREEMENT")]
	public partial class TBL_M_AGREEMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CONTENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCONTENTChanging(string value);
    partial void OnCONTENTChanged();
    #endregion
		
		public TBL_M_AGREEMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENT", DbType="VarChar(MAX)")]
		public string CONTENT
		{
			get
			{
				return this._CONTENT;
			}
			set
			{
				if ((this._CONTENT != value))
				{
					this.OnCONTENTChanging(value);
					this.SendPropertyChanging();
					this._CONTENT = value;
					this.SendPropertyChanged("CONTENT");
					this.OnCONTENTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DISTRICT")]
	public partial class VW_DISTRICT
	{
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_NAME;
		
		public VW_DISTRICT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_NAME", DbType="VarChar(100)")]
		public string DSTRCT_NAME
		{
			get
			{
				return this._DSTRCT_NAME;
			}
			set
			{
				if ((this._DSTRCT_NAME != value))
				{
					this._DSTRCT_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_DISTRICT")]
	public partial class TBL_M_DISTRICT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DSTRCT_CODE;
		
		private string _LOCATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    #endregion
		
		public TBL_M_DISTRICT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(100)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_POSITION")]
	public partial class TBL_M_POSITION
	{
		
		private string _ID_POSITION;
		
		private string _ID_DISTRICT;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _POSITION_FULL;
		
		private string _DSTRCT_CODE;
		
		private string _OCCUP_TYPE;
		
		private string _OCCUP_TYPE_DESC;
		
		private string _GROUP_OCCUP_TYPE;
		
		private string _GROUP_OCCUP_DESC;
		
		private string _COST_CENTRE;
		
		private string _DEPT;
		
		private string _OCCUP_STATUS;
		
		private string _OCCUP_STATUS_DESC;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _DIV_CODE;
		
		private string _DIV_DESC;
		
		private string _POSITION_DESC;
		
		private string _SUPERIOR_ID;
		
		private string _DWH_GROUP_OCCUP_TYPE;
		
		private string _FUNCTIONAL_STRUCTURE;
		
		private string _OCCUP_GRADE;
		
		public TBL_M_POSITION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_POSITION", DbType="VarChar(100)")]
		public string ID_POSITION
		{
			get
			{
				return this._ID_POSITION;
			}
			set
			{
				if ((this._ID_POSITION != value))
				{
					this._ID_POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DISTRICT", DbType="VarChar(100)")]
		public string ID_DISTRICT
		{
			get
			{
				return this._ID_DISTRICT;
			}
			set
			{
				if ((this._ID_DISTRICT != value))
				{
					this._ID_DISTRICT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(100)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_FULL", DbType="VarChar(203)")]
		public string POSITION_FULL
		{
			get
			{
				return this._POSITION_FULL;
			}
			set
			{
				if ((this._POSITION_FULL != value))
				{
					this._POSITION_FULL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCUP_TYPE", DbType="VarChar(100)")]
		public string OCCUP_TYPE
		{
			get
			{
				return this._OCCUP_TYPE;
			}
			set
			{
				if ((this._OCCUP_TYPE != value))
				{
					this._OCCUP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCUP_TYPE_DESC", DbType="VarChar(100)")]
		public string OCCUP_TYPE_DESC
		{
			get
			{
				return this._OCCUP_TYPE_DESC;
			}
			set
			{
				if ((this._OCCUP_TYPE_DESC != value))
				{
					this._OCCUP_TYPE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_OCCUP_TYPE", DbType="VarChar(100)")]
		public string GROUP_OCCUP_TYPE
		{
			get
			{
				return this._GROUP_OCCUP_TYPE;
			}
			set
			{
				if ((this._GROUP_OCCUP_TYPE != value))
				{
					this._GROUP_OCCUP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_OCCUP_DESC", DbType="VarChar(100)")]
		public string GROUP_OCCUP_DESC
		{
			get
			{
				return this._GROUP_OCCUP_DESC;
			}
			set
			{
				if ((this._GROUP_OCCUP_DESC != value))
				{
					this._GROUP_OCCUP_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COST_CENTRE", DbType="VarChar(100)")]
		public string COST_CENTRE
		{
			get
			{
				return this._COST_CENTRE;
			}
			set
			{
				if ((this._COST_CENTRE != value))
				{
					this._COST_CENTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(100)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCUP_STATUS", DbType="VarChar(100)")]
		public string OCCUP_STATUS
		{
			get
			{
				return this._OCCUP_STATUS;
			}
			set
			{
				if ((this._OCCUP_STATUS != value))
				{
					this._OCCUP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCUP_STATUS_DESC", DbType="VarChar(100)")]
		public string OCCUP_STATUS_DESC
		{
			get
			{
				return this._OCCUP_STATUS_DESC;
			}
			set
			{
				if ((this._OCCUP_STATUS_DESC != value))
				{
					this._OCCUP_STATUS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(100)")]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_DESC", DbType="VarChar(100)")]
		public string DIV_DESC
		{
			get
			{
				return this._DIV_DESC;
			}
			set
			{
				if ((this._DIV_DESC != value))
				{
					this._DIV_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_DESC", DbType="VarChar(100)")]
		public string POSITION_DESC
		{
			get
			{
				return this._POSITION_DESC;
			}
			set
			{
				if ((this._POSITION_DESC != value))
				{
					this._POSITION_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWH_GROUP_OCCUP_TYPE", DbType="VarChar(100)")]
		public string DWH_GROUP_OCCUP_TYPE
		{
			get
			{
				return this._DWH_GROUP_OCCUP_TYPE;
			}
			set
			{
				if ((this._DWH_GROUP_OCCUP_TYPE != value))
				{
					this._DWH_GROUP_OCCUP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUNCTIONAL_STRUCTURE", DbType="VarChar(100)")]
		public string FUNCTIONAL_STRUCTURE
		{
			get
			{
				return this._FUNCTIONAL_STRUCTURE;
			}
			set
			{
				if ((this._FUNCTIONAL_STRUCTURE != value))
				{
					this._FUNCTIONAL_STRUCTURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCCUP_GRADE", DbType="VarChar(100)")]
		public string OCCUP_GRADE
		{
			get
			{
				return this._OCCUP_GRADE;
			}
			set
			{
				if ((this._OCCUP_GRADE != value))
				{
					this._OCCUP_GRADE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_MAPPING_APPROVAL")]
	public partial class TBL_M_MAPPING_APPROVAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _APPROVAL_NO;
		
		private System.Nullable<int> _APPROVAL_ACTION;
		
		private System.Nullable<int> _APPROVAL_ORDER;
		
		private string _APPROVAL_FROM;
		
		private string _APPROVAL_TO;
		
		private string _CURR_POSITION_ID;
		
		private string _NEXT_POSITION_ID;
		
		private string _APPROVAL_STATUS;
		
		private string _CURRENT_STATUS;
		
		private string _LOCATION_FROM;
		
		private string _LOCATION_TO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPPROVAL_NOChanging(int value);
    partial void OnAPPROVAL_NOChanged();
    partial void OnAPPROVAL_ACTIONChanging(System.Nullable<int> value);
    partial void OnAPPROVAL_ACTIONChanged();
    partial void OnAPPROVAL_ORDERChanging(System.Nullable<int> value);
    partial void OnAPPROVAL_ORDERChanged();
    partial void OnAPPROVAL_FROMChanging(string value);
    partial void OnAPPROVAL_FROMChanged();
    partial void OnAPPROVAL_TOChanging(string value);
    partial void OnAPPROVAL_TOChanged();
    partial void OnCURR_POSITION_IDChanging(string value);
    partial void OnCURR_POSITION_IDChanged();
    partial void OnNEXT_POSITION_IDChanging(string value);
    partial void OnNEXT_POSITION_IDChanged();
    partial void OnAPPROVAL_STATUSChanging(string value);
    partial void OnAPPROVAL_STATUSChanged();
    partial void OnCURRENT_STATUSChanging(string value);
    partial void OnCURRENT_STATUSChanged();
    partial void OnLOCATION_FROMChanging(string value);
    partial void OnLOCATION_FROMChanged();
    partial void OnLOCATION_TOChanging(string value);
    partial void OnLOCATION_TOChanged();
    #endregion
		
		public TBL_M_MAPPING_APPROVAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_NO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int APPROVAL_NO
		{
			get
			{
				return this._APPROVAL_NO;
			}
			set
			{
				if ((this._APPROVAL_NO != value))
				{
					this.OnAPPROVAL_NOChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_NO = value;
					this.SendPropertyChanged("APPROVAL_NO");
					this.OnAPPROVAL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ACTION", DbType="Int")]
		public System.Nullable<int> APPROVAL_ACTION
		{
			get
			{
				return this._APPROVAL_ACTION;
			}
			set
			{
				if ((this._APPROVAL_ACTION != value))
				{
					this.OnAPPROVAL_ACTIONChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_ACTION = value;
					this.SendPropertyChanged("APPROVAL_ACTION");
					this.OnAPPROVAL_ACTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ORDER", DbType="Int")]
		public System.Nullable<int> APPROVAL_ORDER
		{
			get
			{
				return this._APPROVAL_ORDER;
			}
			set
			{
				if ((this._APPROVAL_ORDER != value))
				{
					this.OnAPPROVAL_ORDERChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_ORDER = value;
					this.SendPropertyChanged("APPROVAL_ORDER");
					this.OnAPPROVAL_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_FROM", DbType="VarChar(10)")]
		public string APPROVAL_FROM
		{
			get
			{
				return this._APPROVAL_FROM;
			}
			set
			{
				if ((this._APPROVAL_FROM != value))
				{
					this.OnAPPROVAL_FROMChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_FROM = value;
					this.SendPropertyChanged("APPROVAL_FROM");
					this.OnAPPROVAL_FROMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_TO", DbType="VarChar(10)")]
		public string APPROVAL_TO
		{
			get
			{
				return this._APPROVAL_TO;
			}
			set
			{
				if ((this._APPROVAL_TO != value))
				{
					this.OnAPPROVAL_TOChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_TO = value;
					this.SendPropertyChanged("APPROVAL_TO");
					this.OnAPPROVAL_TOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURR_POSITION_ID", DbType="VarChar(20)")]
		public string CURR_POSITION_ID
		{
			get
			{
				return this._CURR_POSITION_ID;
			}
			set
			{
				if ((this._CURR_POSITION_ID != value))
				{
					this.OnCURR_POSITION_IDChanging(value);
					this.SendPropertyChanging();
					this._CURR_POSITION_ID = value;
					this.SendPropertyChanged("CURR_POSITION_ID");
					this.OnCURR_POSITION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEXT_POSITION_ID", DbType="VarChar(20)")]
		public string NEXT_POSITION_ID
		{
			get
			{
				return this._NEXT_POSITION_ID;
			}
			set
			{
				if ((this._NEXT_POSITION_ID != value))
				{
					this.OnNEXT_POSITION_IDChanging(value);
					this.SendPropertyChanging();
					this._NEXT_POSITION_ID = value;
					this.SendPropertyChanged("NEXT_POSITION_ID");
					this.OnNEXT_POSITION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_STATUS", DbType="VarChar(50)")]
		public string APPROVAL_STATUS
		{
			get
			{
				return this._APPROVAL_STATUS;
			}
			set
			{
				if ((this._APPROVAL_STATUS != value))
				{
					this.OnAPPROVAL_STATUSChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_STATUS = value;
					this.SendPropertyChanged("APPROVAL_STATUS");
					this.OnAPPROVAL_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENT_STATUS", DbType="VarChar(50)")]
		public string CURRENT_STATUS
		{
			get
			{
				return this._CURRENT_STATUS;
			}
			set
			{
				if ((this._CURRENT_STATUS != value))
				{
					this.OnCURRENT_STATUSChanging(value);
					this.SendPropertyChanging();
					this._CURRENT_STATUS = value;
					this.SendPropertyChanged("CURRENT_STATUS");
					this.OnCURRENT_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_FROM", DbType="VarChar(100)")]
		public string LOCATION_FROM
		{
			get
			{
				return this._LOCATION_FROM;
			}
			set
			{
				if ((this._LOCATION_FROM != value))
				{
					this.OnLOCATION_FROMChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_FROM = value;
					this.SendPropertyChanged("LOCATION_FROM");
					this.OnLOCATION_FROMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION_TO", DbType="VarChar(100)")]
		public string LOCATION_TO
		{
			get
			{
				return this._LOCATION_TO;
			}
			set
			{
				if ((this._LOCATION_TO != value))
				{
					this.OnLOCATION_TOChanging(value);
					this.SendPropertyChanging();
					this._LOCATION_TO = value;
					this.SendPropertyChanged("LOCATION_TO");
					this.OnLOCATION_TOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
