#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLANT_PPE.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PLANT_PPE_NEW_KPT")]
	public partial class DB_PLANT_PPEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void UpdateTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void DeleteTBL_R_SUB_MENU(TBL_R_SUB_MENU instance);
    partial void InsertTBL_M_ROLE(TBL_M_ROLE instance);
    partial void UpdateTBL_M_ROLE(TBL_M_ROLE instance);
    partial void DeleteTBL_M_ROLE(TBL_M_ROLE instance);
    partial void InsertTBL_M_USER_APPROVAL(TBL_M_USER_APPROVAL instance);
    partial void UpdateTBL_M_USER_APPROVAL(TBL_M_USER_APPROVAL instance);
    partial void DeleteTBL_M_USER_APPROVAL(TBL_M_USER_APPROVAL instance);
    partial void InsertTBL_M_USER(TBL_M_USER instance);
    partial void UpdateTBL_M_USER(TBL_M_USER instance);
    partial void DeleteTBL_M_USER(TBL_M_USER instance);
    partial void InsertTBL_M_DISTRICT(TBL_M_DISTRICT instance);
    partial void UpdateTBL_M_DISTRICT(TBL_M_DISTRICT instance);
    partial void DeleteTBL_M_DISTRICT(TBL_M_DISTRICT instance);
    partial void InsertTBL_T_PPE(TBL_T_PPE instance);
    partial void UpdateTBL_T_PPE(TBL_T_PPE instance);
    partial void DeleteTBL_T_PPE(TBL_T_PPE instance);
    #endregion
		
		public DB_PLANT_PPEDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_PLANT_PPE_NEW_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_PPEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_PPEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_PPEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PLANT_PPEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_R_SUB_MENU> TBL_R_SUB_MENUs
		{
			get
			{
				return this.GetTable<TBL_R_SUB_MENU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_ROLE> TBL_M_ROLEs
		{
			get
			{
				return this.GetTable<TBL_M_ROLE>();
			}
		}
		
		public System.Data.Linq.Table<VW_KARYAWAN_ALL> VW_KARYAWAN_ALLs
		{
			get
			{
				return this.GetTable<VW_KARYAWAN_ALL>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_MENU> VW_R_MENUs
		{
			get
			{
				return this.GetTable<VW_R_MENU>();
			}
		}
		
		public System.Data.Linq.Table<VW_DISTRICT> VW_DISTRICTs
		{
			get
			{
				return this.GetTable<VW_DISTRICT>();
			}
		}
		
		public System.Data.Linq.Table<VW_LOCATION> VW_LOCATIONs
		{
			get
			{
				return this.GetTable<VW_LOCATION>();
			}
		}
		
		public System.Data.Linq.Table<VW_T_PPE> VW_T_PPEs
		{
			get
			{
				return this.GetTable<VW_T_PPE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_USER_APPROVAL> TBL_M_USER_APPROVALs
		{
			get
			{
				return this.GetTable<TBL_M_USER_APPROVAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_USER> TBL_M_USERs
		{
			get
			{
				return this.GetTable<TBL_M_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_MAPPING_APPROVALSS> TBL_M_MAPPING_APPROVALSSes
		{
			get
			{
				return this.GetTable<TBL_M_MAPPING_APPROVALSS>();
			}
		}
		
		public System.Data.Linq.Table<VW_MSF68C> VW_MSF68Cs
		{
			get
			{
				return this.GetTable<VW_MSF68C>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_DISTRICT_LOCATION> VW_R_DISTRICT_LOCATIONs
		{
			get
			{
				return this.GetTable<VW_R_DISTRICT_LOCATION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MASTER_KARYAWAN_ALL> TBL_R_MASTER_KARYAWAN_ALLs
		{
			get
			{
				return this.GetTable<TBL_R_MASTER_KARYAWAN_ALL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_DISTRICT> TBL_M_DISTRICTs
		{
			get
			{
				return this.GetTable<TBL_M_DISTRICT>();
			}
		}
		
		public System.Data.Linq.Table<VW_User> VW_Users
		{
			get
			{
				return this.GetTable<VW_User>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_PPE> TBL_T_PPEs
		{
			get
			{
				return this.GetTable<TBL_T_PPE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_SUB_MENU")]
	public partial class TBL_R_SUB_MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Sub_Menu;
		
		private System.Nullable<int> _ID_Menu;
		
		private string _Sub_Menu_Description;
		
		private string _Link_Sub_Menu;
		
		private string _Akses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Sub_MenuChanging(int value);
    partial void OnID_Sub_MenuChanged();
    partial void OnID_MenuChanging(System.Nullable<int> value);
    partial void OnID_MenuChanged();
    partial void OnSub_Menu_DescriptionChanging(string value);
    partial void OnSub_Menu_DescriptionChanged();
    partial void OnLink_Sub_MenuChanging(string value);
    partial void OnLink_Sub_MenuChanged();
    partial void OnAksesChanging(string value);
    partial void OnAksesChanged();
    #endregion
		
		public TBL_R_SUB_MENU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sub_Menu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Sub_Menu
		{
			get
			{
				return this._ID_Sub_Menu;
			}
			set
			{
				if ((this._ID_Sub_Menu != value))
				{
					this.OnID_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Sub_Menu = value;
					this.SendPropertyChanged("ID_Sub_Menu");
					this.OnID_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int")]
		public System.Nullable<int> ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this.OnID_MenuChanging(value);
					this.SendPropertyChanging();
					this._ID_Menu = value;
					this.SendPropertyChanged("ID_Menu");
					this.OnID_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu_Description", DbType="NVarChar(150)")]
		public string Sub_Menu_Description
		{
			get
			{
				return this._Sub_Menu_Description;
			}
			set
			{
				if ((this._Sub_Menu_Description != value))
				{
					this.OnSub_Menu_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Sub_Menu_Description = value;
					this.SendPropertyChanged("Sub_Menu_Description");
					this.OnSub_Menu_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Sub_Menu", DbType="NVarChar(250)")]
		public string Link_Sub_Menu
		{
			get
			{
				return this._Link_Sub_Menu;
			}
			set
			{
				if ((this._Link_Sub_Menu != value))
				{
					this.OnLink_Sub_MenuChanging(value);
					this.SendPropertyChanging();
					this._Link_Sub_Menu = value;
					this.SendPropertyChanged("Link_Sub_Menu");
					this.OnLink_Sub_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Akses", DbType="VarChar(50)")]
		public string Akses
		{
			get
			{
				return this._Akses;
			}
			set
			{
				if ((this._Akses != value))
				{
					this.OnAksesChanging(value);
					this.SendPropertyChanging();
					this._Akses = value;
					this.SendPropertyChanged("Akses");
					this.OnAksesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_ROLE")]
	public partial class TBL_M_ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RoleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public TBL_M_ROLE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KARYAWAN_ALL")]
	public partial class VW_KARYAWAN_ALL
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _EMP_STATUS;
		
		private string _GENDER_CODE;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _EMAIL;
		
		private string _ACTIVE_STATUS;
		
		public VW_KARYAWAN_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(100)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(100)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(100)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(100)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(100)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(100)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(100)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(100)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(100)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(100)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(100)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="VarChar(100)")]
		public string ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_MENU")]
	public partial class VW_R_MENU
	{
		
		private int _ID;
		
		private string _RoleName;
		
		private int _ID_Menu;
		
		private string _Name_Menu;
		
		private System.Nullable<int> _Sub_Menu;
		
		private string _Icon_Menu;
		
		private string _Link_Menu;
		
		private System.Nullable<int> _Order;
		
		public VW_R_MENU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Menu", DbType="Int NOT NULL")]
		public int ID_Menu
		{
			get
			{
				return this._ID_Menu;
			}
			set
			{
				if ((this._ID_Menu != value))
				{
					this._ID_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Menu", DbType="NVarChar(50)")]
		public string Name_Menu
		{
			get
			{
				return this._Name_Menu;
			}
			set
			{
				if ((this._Name_Menu != value))
				{
					this._Name_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Menu", DbType="Int")]
		public System.Nullable<int> Sub_Menu
		{
			get
			{
				return this._Sub_Menu;
			}
			set
			{
				if ((this._Sub_Menu != value))
				{
					this._Sub_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon_Menu", DbType="NVarChar(150)")]
		public string Icon_Menu
		{
			get
			{
				return this._Icon_Menu;
			}
			set
			{
				if ((this._Icon_Menu != value))
				{
					this._Icon_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Menu", DbType="NVarChar(250)")]
		public string Link_Menu
		{
			get
			{
				return this._Link_Menu;
			}
			set
			{
				if ((this._Link_Menu != value))
				{
					this._Link_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order]", Storage="_Order", DbType="Int")]
		public System.Nullable<int> Order
		{
			get
			{
				return this._Order;
			}
			set
			{
				if ((this._Order != value))
				{
					this._Order = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DISTRICT")]
	public partial class VW_DISTRICT
	{
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_NAME;
		
		public VW_DISTRICT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_NAME", DbType="VarChar(100)")]
		public string DSTRCT_NAME
		{
			get
			{
				return this._DSTRCT_NAME;
			}
			set
			{
				if ((this._DSTRCT_NAME != value))
				{
					this._DSTRCT_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_LOCATION")]
	public partial class VW_LOCATION
	{
		
		private string _TABLE_CODE;
		
		private string _TABLE_DESC;
		
		public VW_LOCATION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CODE", DbType="Char(18) NOT NULL", CanBeNull=false)]
		public string TABLE_CODE
		{
			get
			{
				return this._TABLE_CODE;
			}
			set
			{
				if ((this._TABLE_CODE != value))
				{
					this._TABLE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_DESC", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string TABLE_DESC
		{
			get
			{
				return this._TABLE_DESC;
			}
			set
			{
				if ((this._TABLE_DESC != value))
				{
					this._TABLE_DESC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_T_PPE")]
	public partial class VW_T_PPE
	{
		
		private int _ID;
		
		private string _PPE_NO;
		
		private System.Nullable<int> _APPROVAL_ORDER;
		
		private string _CURR_POSITION_ID;
		
		private string _NEXT_POSITION_ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _DISTRICT_FROM;
		
		private string _DISTRICT_TO;
		
		private string _LOC_FROM;
		
		private string _LOC_TO;
		
		private string _EQUIP_NO;
		
		private string _EGI;
		
		private string _EQUIP_CLASS;
		
		private string _SERIAL_NO;
		
		private string _PPE_DESC;
		
		private string _POSISI_PPE;
		
		private string _STATUS;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _CREATED_BY;
		
		private string _NAME;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
		private string _UPDATED_BY;
		
		private string _UPDATED_NAME;
		
		private string _REMARKS;
		
		private string _PATH_ATTACHMENT;
		
		private string _UPLOAD_FORM_CAAB;
		
		private System.Nullable<System.DateTime> _DATE_RECEIVED_SM;
		
		private string _BERITA_ACARA_SM;
		
		public VW_T_PPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPE_NO", DbType="VarChar(200)")]
		public string PPE_NO
		{
			get
			{
				return this._PPE_NO;
			}
			set
			{
				if ((this._PPE_NO != value))
				{
					this._PPE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ORDER", DbType="Int")]
		public System.Nullable<int> APPROVAL_ORDER
		{
			get
			{
				return this._APPROVAL_ORDER;
			}
			set
			{
				if ((this._APPROVAL_ORDER != value))
				{
					this._APPROVAL_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURR_POSITION_ID", DbType="VarChar(20)")]
		public string CURR_POSITION_ID
		{
			get
			{
				return this._CURR_POSITION_ID;
			}
			set
			{
				if ((this._CURR_POSITION_ID != value))
				{
					this._CURR_POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEXT_POSITION_ID", DbType="VarChar(20)")]
		public string NEXT_POSITION_ID
		{
			get
			{
				return this._NEXT_POSITION_ID;
			}
			set
			{
				if ((this._NEXT_POSITION_ID != value))
				{
					this._NEXT_POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT_FROM", DbType="VarChar(50)")]
		public string DISTRICT_FROM
		{
			get
			{
				return this._DISTRICT_FROM;
			}
			set
			{
				if ((this._DISTRICT_FROM != value))
				{
					this._DISTRICT_FROM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT_TO", DbType="VarChar(50)")]
		public string DISTRICT_TO
		{
			get
			{
				return this._DISTRICT_TO;
			}
			set
			{
				if ((this._DISTRICT_TO != value))
				{
					this._DISTRICT_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_FROM", DbType="VarChar(50)")]
		public string LOC_FROM
		{
			get
			{
				return this._LOC_FROM;
			}
			set
			{
				if ((this._LOC_FROM != value))
				{
					this._LOC_FROM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_TO", DbType="VarChar(50)")]
		public string LOC_TO
		{
			get
			{
				return this._LOC_TO;
			}
			set
			{
				if ((this._LOC_TO != value))
				{
					this._LOC_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIP_NO", DbType="VarChar(50)")]
		public string EQUIP_NO
		{
			get
			{
				return this._EQUIP_NO;
			}
			set
			{
				if ((this._EQUIP_NO != value))
				{
					this._EQUIP_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGI", DbType="VarChar(20)")]
		public string EGI
		{
			get
			{
				return this._EGI;
			}
			set
			{
				if ((this._EGI != value))
				{
					this._EGI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIP_CLASS", DbType="VarChar(10)")]
		public string EQUIP_CLASS
		{
			get
			{
				return this._EQUIP_CLASS;
			}
			set
			{
				if ((this._EQUIP_CLASS != value))
				{
					this._EQUIP_CLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIAL_NO", DbType="VarChar(50)")]
		public string SERIAL_NO
		{
			get
			{
				return this._SERIAL_NO;
			}
			set
			{
				if ((this._SERIAL_NO != value))
				{
					this._SERIAL_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPE_DESC", DbType="VarChar(200)")]
		public string PPE_DESC
		{
			get
			{
				return this._PPE_DESC;
			}
			set
			{
				if ((this._PPE_DESC != value))
				{
					this._PPE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSISI_PPE", DbType="VarChar(100)")]
		public string POSISI_PPE
		{
			get
			{
				return this._POSISI_PPE;
			}
			set
			{
				if ((this._POSISI_PPE != value))
				{
					this._POSISI_PPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(50)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this._UPDATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="VarChar(50)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this._UPDATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_NAME", DbType="VarChar(61)")]
		public string UPDATED_NAME
		{
			get
			{
				return this._UPDATED_NAME;
			}
			set
			{
				if ((this._UPDATED_NAME != value))
				{
					this._UPDATED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATH_ATTACHMENT", DbType="VarChar(200)")]
		public string PATH_ATTACHMENT
		{
			get
			{
				return this._PATH_ATTACHMENT;
			}
			set
			{
				if ((this._PATH_ATTACHMENT != value))
				{
					this._PATH_ATTACHMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_FORM_CAAB", DbType="VarChar(200)")]
		public string UPLOAD_FORM_CAAB
		{
			get
			{
				return this._UPLOAD_FORM_CAAB;
			}
			set
			{
				if ((this._UPLOAD_FORM_CAAB != value))
				{
					this._UPLOAD_FORM_CAAB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIVED_SM", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_RECEIVED_SM
		{
			get
			{
				return this._DATE_RECEIVED_SM;
			}
			set
			{
				if ((this._DATE_RECEIVED_SM != value))
				{
					this._DATE_RECEIVED_SM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BERITA_ACARA_SM", DbType="VarChar(MAX)")]
		public string BERITA_ACARA_SM
		{
			get
			{
				return this._BERITA_ACARA_SM;
			}
			set
			{
				if ((this._BERITA_ACARA_SM != value))
				{
					this._BERITA_ACARA_SM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_USER_APPROVAL")]
	public partial class TBL_M_USER_APPROVAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Position_id;
		
		private string _Employee_id;
		
		private string _Name;
		
		private string _sub_menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPosition_idChanging(string value);
    partial void OnPosition_idChanged();
    partial void OnEmployee_idChanging(string value);
    partial void OnEmployee_idChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void Onsub_menuChanging(string value);
    partial void Onsub_menuChanged();
    #endregion
		
		public TBL_M_USER_APPROVAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position_id", DbType="VarChar(50)")]
		public string Position_id
		{
			get
			{
				return this._Position_id;
			}
			set
			{
				if ((this._Position_id != value))
				{
					this.OnPosition_idChanging(value);
					this.SendPropertyChanging();
					this._Position_id = value;
					this.SendPropertyChanged("Position_id");
					this.OnPosition_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_id", DbType="VarChar(50)")]
		public string Employee_id
		{
			get
			{
				return this._Employee_id;
			}
			set
			{
				if ((this._Employee_id != value))
				{
					this.OnEmployee_idChanging(value);
					this.SendPropertyChanging();
					this._Employee_id = value;
					this.SendPropertyChanged("Employee_id");
					this.OnEmployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_menu", DbType="VarChar(50)")]
		public string sub_menu
		{
			get
			{
				return this._sub_menu;
			}
			set
			{
				if ((this._sub_menu != value))
				{
					this.Onsub_menuChanging(value);
					this.SendPropertyChanging();
					this._sub_menu = value;
					this.SendPropertyChanged("sub_menu");
					this.Onsub_menuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_USER")]
	public partial class TBL_M_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Role;
		
		private string _Username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RoleChanging(int value);
    partial void OnID_RoleChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public TBL_M_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_MAPPING_APPROVALSS")]
	public partial class TBL_M_MAPPING_APPROVALSS
	{
		
		private System.Nullable<int> _APPROVAL_ACTION;
		
		private System.Nullable<int> _APPROVAL_ORDER;
		
		private string _APPROVAL_FROM;
		
		private string _APPROVAL_TO;
		
		private string _CURR_POSITION_ID;
		
		private string _NEXT_POSITION_ID;
		
		private string _APPROVAL_STATUS;
		
		private string _CURRENT_STATUS;
		
		public TBL_M_MAPPING_APPROVALSS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ACTION", DbType="Int")]
		public System.Nullable<int> APPROVAL_ACTION
		{
			get
			{
				return this._APPROVAL_ACTION;
			}
			set
			{
				if ((this._APPROVAL_ACTION != value))
				{
					this._APPROVAL_ACTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ORDER", DbType="Int")]
		public System.Nullable<int> APPROVAL_ORDER
		{
			get
			{
				return this._APPROVAL_ORDER;
			}
			set
			{
				if ((this._APPROVAL_ORDER != value))
				{
					this._APPROVAL_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_FROM", DbType="VarChar(10)")]
		public string APPROVAL_FROM
		{
			get
			{
				return this._APPROVAL_FROM;
			}
			set
			{
				if ((this._APPROVAL_FROM != value))
				{
					this._APPROVAL_FROM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_TO", DbType="VarChar(10)")]
		public string APPROVAL_TO
		{
			get
			{
				return this._APPROVAL_TO;
			}
			set
			{
				if ((this._APPROVAL_TO != value))
				{
					this._APPROVAL_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURR_POSITION_ID", DbType="VarChar(20)")]
		public string CURR_POSITION_ID
		{
			get
			{
				return this._CURR_POSITION_ID;
			}
			set
			{
				if ((this._CURR_POSITION_ID != value))
				{
					this._CURR_POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEXT_POSITION_ID", DbType="VarChar(20)")]
		public string NEXT_POSITION_ID
		{
			get
			{
				return this._NEXT_POSITION_ID;
			}
			set
			{
				if ((this._NEXT_POSITION_ID != value))
				{
					this._NEXT_POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_STATUS", DbType="VarChar(50)")]
		public string APPROVAL_STATUS
		{
			get
			{
				return this._APPROVAL_STATUS;
			}
			set
			{
				if ((this._APPROVAL_STATUS != value))
				{
					this._APPROVAL_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENT_STATUS", DbType="VarChar(50)")]
		public string CURRENT_STATUS
		{
			get
			{
				return this._CURRENT_STATUS;
			}
			set
			{
				if ((this._CURRENT_STATUS != value))
				{
					this._CURRENT_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_MSF68C")]
	public partial class VW_MSF68C
	{
		
		private string _ACCT_PROFILE;
		
		private string _ACCT_RECON_TYPE;
		
		private string _DSTRCT_CODE;
		
		private string _ACCOUNT_DESC;
		
		private string _ACCOUNT_UNIT;
		
		private char _ACCT_TYPE;
		
		private decimal _ACCUM_DEPR;
		
		private decimal _COR_RATE;
		
		private string _COST_DSTRCT_CDE;
		
		private string _CREATION_DATE;
		
		private string _CREATION_TIME;
		
		private string _CREATION_USER;
		
		private decimal _DEPR_RATE;
		
		private string _LAST_MOD_DATE;
		
		private string _LAST_MOD_TIME;
		
		private string _LAST_MOD_USER;
		
		private char _REVAL_METHOD;
		
		private decimal _SALV_RATE;
		
		private string _LAST_MOD_EMP;
		
		public VW_MSF68C()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCT_PROFILE", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string ACCT_PROFILE
		{
			get
			{
				return this._ACCT_PROFILE;
			}
			set
			{
				if ((this._ACCT_PROFILE != value))
				{
					this._ACCT_PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCT_RECON_TYPE", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string ACCT_RECON_TYPE
		{
			get
			{
				return this._ACCT_RECON_TYPE;
			}
			set
			{
				if ((this._ACCT_RECON_TYPE != value))
				{
					this._ACCT_RECON_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_DESC", DbType="Char(40) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_DESC
		{
			get
			{
				return this._ACCOUNT_DESC;
			}
			set
			{
				if ((this._ACCOUNT_DESC != value))
				{
					this._ACCOUNT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_UNIT", DbType="Char(24) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_UNIT
		{
			get
			{
				return this._ACCOUNT_UNIT;
			}
			set
			{
				if ((this._ACCOUNT_UNIT != value))
				{
					this._ACCOUNT_UNIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCT_TYPE", DbType="Char(1) NOT NULL")]
		public char ACCT_TYPE
		{
			get
			{
				return this._ACCT_TYPE;
			}
			set
			{
				if ((this._ACCT_TYPE != value))
				{
					this._ACCT_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCUM_DEPR", DbType="Decimal(21,2) NOT NULL")]
		public decimal ACCUM_DEPR
		{
			get
			{
				return this._ACCUM_DEPR;
			}
			set
			{
				if ((this._ACCUM_DEPR != value))
				{
					this._ACCUM_DEPR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COR_RATE", DbType="Decimal(7,4) NOT NULL")]
		public decimal COR_RATE
		{
			get
			{
				return this._COR_RATE;
			}
			set
			{
				if ((this._COR_RATE != value))
				{
					this._COR_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COST_DSTRCT_CDE", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string COST_DSTRCT_CDE
		{
			get
			{
				return this._COST_DSTRCT_CDE;
			}
			set
			{
				if ((this._COST_DSTRCT_CDE != value))
				{
					this._COST_DSTRCT_CDE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this._CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_TIME", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string CREATION_TIME
		{
			get
			{
				return this._CREATION_TIME;
			}
			set
			{
				if ((this._CREATION_TIME != value))
				{
					this._CREATION_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_USER", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string CREATION_USER
		{
			get
			{
				return this._CREATION_USER;
			}
			set
			{
				if ((this._CREATION_USER != value))
				{
					this._CREATION_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPR_RATE", DbType="Decimal(7,4) NOT NULL")]
		public decimal DEPR_RATE
		{
			get
			{
				return this._DEPR_RATE;
			}
			set
			{
				if ((this._DEPR_RATE != value))
				{
					this._DEPR_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_DATE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_DATE
		{
			get
			{
				return this._LAST_MOD_DATE;
			}
			set
			{
				if ((this._LAST_MOD_DATE != value))
				{
					this._LAST_MOD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_TIME", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_TIME
		{
			get
			{
				return this._LAST_MOD_TIME;
			}
			set
			{
				if ((this._LAST_MOD_TIME != value))
				{
					this._LAST_MOD_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_USER", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_USER
		{
			get
			{
				return this._LAST_MOD_USER;
			}
			set
			{
				if ((this._LAST_MOD_USER != value))
				{
					this._LAST_MOD_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVAL_METHOD", DbType="Char(1) NOT NULL")]
		public char REVAL_METHOD
		{
			get
			{
				return this._REVAL_METHOD;
			}
			set
			{
				if ((this._REVAL_METHOD != value))
				{
					this._REVAL_METHOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALV_RATE", DbType="Decimal(7,4) NOT NULL")]
		public decimal SALV_RATE
		{
			get
			{
				return this._SALV_RATE;
			}
			set
			{
				if ((this._SALV_RATE != value))
				{
					this._SALV_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MOD_EMP", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string LAST_MOD_EMP
		{
			get
			{
				return this._LAST_MOD_EMP;
			}
			set
			{
				if ((this._LAST_MOD_EMP != value))
				{
					this._LAST_MOD_EMP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_DISTRICT_LOCATION")]
	public partial class VW_R_DISTRICT_LOCATION
	{
		
		private string _DSTRCT_CODE;
		
		private string _EQUIP_LOCATION;
		
		public VW_R_DISTRICT_LOCATION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIP_LOCATION", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string EQUIP_LOCATION
		{
			get
			{
				return this._EQUIP_LOCATION;
			}
			set
			{
				if ((this._EQUIP_LOCATION != value))
				{
					this._EQUIP_LOCATION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MASTER_KARYAWAN_ALL")]
	public partial class TBL_R_MASTER_KARYAWAN_ALL
	{
		
		private string _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _EMP_STATUS;
		
		private string _GENDER_CODE;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _EMAIL;
		
		private string _ACTIVE_STATUS;
		
		public TBL_R_MASTER_KARYAWAN_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="NVarChar(8)")]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(100)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(100)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(100)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(100)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(100)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(100)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(100)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(100)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(100)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(100)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(100)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(100)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(100)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(100)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="VarChar(100)")]
		public string ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_DISTRICT")]
	public partial class TBL_M_DISTRICT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TABLE_CODE;
		
		private string _TABLE_DESC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTABLE_CODEChanging(string value);
    partial void OnTABLE_CODEChanged();
    partial void OnTABLE_DESCChanging(string value);
    partial void OnTABLE_DESCChanged();
    #endregion
		
		public TBL_M_DISTRICT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_CODE", DbType="Char(18)")]
		public string TABLE_CODE
		{
			get
			{
				return this._TABLE_CODE;
			}
			set
			{
				if ((this._TABLE_CODE != value))
				{
					this.OnTABLE_CODEChanging(value);
					this.SendPropertyChanging();
					this._TABLE_CODE = value;
					this.SendPropertyChanged("TABLE_CODE");
					this.OnTABLE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TABLE_DESC", DbType="Char(50)")]
		public string TABLE_DESC
		{
			get
			{
				return this._TABLE_DESC;
			}
			set
			{
				if ((this._TABLE_DESC != value))
				{
					this.OnTABLE_DESCChanging(value);
					this.SendPropertyChanging();
					this._TABLE_DESC = value;
					this.SendPropertyChanged("TABLE_DESC");
					this.OnTABLE_DESCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_User")]
	public partial class VW_User
	{
		
		private int _ID_Role;
		
		private string _Username;
		
		private string _NAME;
		
		private string _EMAIL;
		
		private string _DSTRCT_CODE;
		
		private string _RoleName;
		
		private string _POSITION_ID;
		
		public VW_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int NOT NULL")]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this._ID_Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(61)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(150)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="Char(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_PPE")]
	public partial class TBL_T_PPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID_PPE;
		
		private int _ID;
		
		private System.Nullable<int> _APPROVAL_ORDER;
		
		private string _PPE_NO;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _DISTRICT_FROM;
		
		private string _DISTRICT_TO;
		
		private string _LOC_FROM;
		
		private string _LOC_TO;
		
		private string _EQUIP_NO;
		
		private string _EGI;
		
		private string _EQUIP_CLASS;
		
		private string _SERIAL_NO;
		
		private string _PPE_DESC;
		
		private string _POSISI_PPE;
		
		private string _STATUS;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _CREATED_BY;
		
		private string _CREATED_POS_BY;
		
		private System.Nullable<System.DateTime> _UPDATED_DATE;
		
		private string _UPDATED_BY;
		
		private string _REMARKS;
		
		private string _PATH_ATTACHMENT;
		
		private string _UPLOAD_FORM_CAAB;
		
		private string _URL_FORM_SH;
		
		private string _URL_FORM_PLNTMNGR;
		
		private string _URL_FORM_PLNTDH;
		
		private string _URL_FORM_PM_PENGIRIM;
		
		private string _URL_FORM_PM_PENERIMA;
		
		private string _URL_FORM_DIVHEAD_ENG;
		
		private string _URL_FORM_DIVHEAD_OPR;
		
		private string _URL_FORM_DONE;
		
		private System.Nullable<System.DateTime> _DATE_RECEIVED_SM;
		
		private string _BERITA_ACARA_SM;
		
		private System.Nullable<int> _FLAG;
		
		private string _FLAG_REMARKS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PPEChanging(System.Guid value);
    partial void OnID_PPEChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAPPROVAL_ORDERChanging(System.Nullable<int> value);
    partial void OnAPPROVAL_ORDERChanged();
    partial void OnPPE_NOChanging(string value);
    partial void OnPPE_NOChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnDISTRICT_FROMChanging(string value);
    partial void OnDISTRICT_FROMChanged();
    partial void OnDISTRICT_TOChanging(string value);
    partial void OnDISTRICT_TOChanged();
    partial void OnLOC_FROMChanging(string value);
    partial void OnLOC_FROMChanged();
    partial void OnLOC_TOChanging(string value);
    partial void OnLOC_TOChanged();
    partial void OnEQUIP_NOChanging(string value);
    partial void OnEQUIP_NOChanged();
    partial void OnEGIChanging(string value);
    partial void OnEGIChanged();
    partial void OnEQUIP_CLASSChanging(string value);
    partial void OnEQUIP_CLASSChanged();
    partial void OnSERIAL_NOChanging(string value);
    partial void OnSERIAL_NOChanged();
    partial void OnPPE_DESCChanging(string value);
    partial void OnPPE_DESCChanged();
    partial void OnPOSISI_PPEChanging(string value);
    partial void OnPOSISI_PPEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnCREATED_BYChanging(string value);
    partial void OnCREATED_BYChanged();
    partial void OnCREATED_POS_BYChanging(string value);
    partial void OnCREATED_POS_BYChanged();
    partial void OnUPDATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATED_DATEChanged();
    partial void OnUPDATED_BYChanging(string value);
    partial void OnUPDATED_BYChanged();
    partial void OnREMARKSChanging(string value);
    partial void OnREMARKSChanged();
    partial void OnPATH_ATTACHMENTChanging(string value);
    partial void OnPATH_ATTACHMENTChanged();
    partial void OnUPLOAD_FORM_CAABChanging(string value);
    partial void OnUPLOAD_FORM_CAABChanged();
    partial void OnURL_FORM_SHChanging(string value);
    partial void OnURL_FORM_SHChanged();
    partial void OnURL_FORM_PLNTMNGRChanging(string value);
    partial void OnURL_FORM_PLNTMNGRChanged();
    partial void OnURL_FORM_PLNTDHChanging(string value);
    partial void OnURL_FORM_PLNTDHChanged();
    partial void OnURL_FORM_PM_PENGIRIMChanging(string value);
    partial void OnURL_FORM_PM_PENGIRIMChanged();
    partial void OnURL_FORM_PM_PENERIMAChanging(string value);
    partial void OnURL_FORM_PM_PENERIMAChanged();
    partial void OnURL_FORM_DIVHEAD_ENGChanging(string value);
    partial void OnURL_FORM_DIVHEAD_ENGChanged();
    partial void OnURL_FORM_DIVHEAD_OPRChanging(string value);
    partial void OnURL_FORM_DIVHEAD_OPRChanged();
    partial void OnURL_FORM_DONEChanging(string value);
    partial void OnURL_FORM_DONEChanged();
    partial void OnDATE_RECEIVED_SMChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_RECEIVED_SMChanged();
    partial void OnBERITA_ACARA_SMChanging(string value);
    partial void OnBERITA_ACARA_SMChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    partial void OnFLAG_REMARKSChanging(string value);
    partial void OnFLAG_REMARKSChanged();
    #endregion
		
		public TBL_T_PPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PPE", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID_PPE
		{
			get
			{
				return this._ID_PPE;
			}
			set
			{
				if ((this._ID_PPE != value))
				{
					this.OnID_PPEChanging(value);
					this.SendPropertyChanging();
					this._ID_PPE = value;
					this.SendPropertyChanged("ID_PPE");
					this.OnID_PPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVAL_ORDER", DbType="Int")]
		public System.Nullable<int> APPROVAL_ORDER
		{
			get
			{
				return this._APPROVAL_ORDER;
			}
			set
			{
				if ((this._APPROVAL_ORDER != value))
				{
					this.OnAPPROVAL_ORDERChanging(value);
					this.SendPropertyChanging();
					this._APPROVAL_ORDER = value;
					this.SendPropertyChanged("APPROVAL_ORDER");
					this.OnAPPROVAL_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPE_NO", DbType="VarChar(200)")]
		public string PPE_NO
		{
			get
			{
				return this._PPE_NO;
			}
			set
			{
				if ((this._PPE_NO != value))
				{
					this.OnPPE_NOChanging(value);
					this.SendPropertyChanging();
					this._PPE_NO = value;
					this.SendPropertyChanged("PPE_NO");
					this.OnPPE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT_FROM", DbType="VarChar(50)")]
		public string DISTRICT_FROM
		{
			get
			{
				return this._DISTRICT_FROM;
			}
			set
			{
				if ((this._DISTRICT_FROM != value))
				{
					this.OnDISTRICT_FROMChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT_FROM = value;
					this.SendPropertyChanged("DISTRICT_FROM");
					this.OnDISTRICT_FROMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT_TO", DbType="VarChar(50)")]
		public string DISTRICT_TO
		{
			get
			{
				return this._DISTRICT_TO;
			}
			set
			{
				if ((this._DISTRICT_TO != value))
				{
					this.OnDISTRICT_TOChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT_TO = value;
					this.SendPropertyChanged("DISTRICT_TO");
					this.OnDISTRICT_TOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_FROM", DbType="VarChar(50)")]
		public string LOC_FROM
		{
			get
			{
				return this._LOC_FROM;
			}
			set
			{
				if ((this._LOC_FROM != value))
				{
					this.OnLOC_FROMChanging(value);
					this.SendPropertyChanging();
					this._LOC_FROM = value;
					this.SendPropertyChanged("LOC_FROM");
					this.OnLOC_FROMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_TO", DbType="VarChar(50)")]
		public string LOC_TO
		{
			get
			{
				return this._LOC_TO;
			}
			set
			{
				if ((this._LOC_TO != value))
				{
					this.OnLOC_TOChanging(value);
					this.SendPropertyChanging();
					this._LOC_TO = value;
					this.SendPropertyChanged("LOC_TO");
					this.OnLOC_TOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIP_NO", DbType="VarChar(50)")]
		public string EQUIP_NO
		{
			get
			{
				return this._EQUIP_NO;
			}
			set
			{
				if ((this._EQUIP_NO != value))
				{
					this.OnEQUIP_NOChanging(value);
					this.SendPropertyChanging();
					this._EQUIP_NO = value;
					this.SendPropertyChanged("EQUIP_NO");
					this.OnEQUIP_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGI", DbType="VarChar(20)")]
		public string EGI
		{
			get
			{
				return this._EGI;
			}
			set
			{
				if ((this._EGI != value))
				{
					this.OnEGIChanging(value);
					this.SendPropertyChanging();
					this._EGI = value;
					this.SendPropertyChanged("EGI");
					this.OnEGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIP_CLASS", DbType="VarChar(10)")]
		public string EQUIP_CLASS
		{
			get
			{
				return this._EQUIP_CLASS;
			}
			set
			{
				if ((this._EQUIP_CLASS != value))
				{
					this.OnEQUIP_CLASSChanging(value);
					this.SendPropertyChanging();
					this._EQUIP_CLASS = value;
					this.SendPropertyChanged("EQUIP_CLASS");
					this.OnEQUIP_CLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIAL_NO", DbType="VarChar(50)")]
		public string SERIAL_NO
		{
			get
			{
				return this._SERIAL_NO;
			}
			set
			{
				if ((this._SERIAL_NO != value))
				{
					this.OnSERIAL_NOChanging(value);
					this.SendPropertyChanging();
					this._SERIAL_NO = value;
					this.SendPropertyChanged("SERIAL_NO");
					this.OnSERIAL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPE_DESC", DbType="VarChar(200)")]
		public string PPE_DESC
		{
			get
			{
				return this._PPE_DESC;
			}
			set
			{
				if ((this._PPE_DESC != value))
				{
					this.OnPPE_DESCChanging(value);
					this.SendPropertyChanging();
					this._PPE_DESC = value;
					this.SendPropertyChanged("PPE_DESC");
					this.OnPPE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSISI_PPE", DbType="VarChar(100)")]
		public string POSISI_PPE
		{
			get
			{
				return this._POSISI_PPE;
			}
			set
			{
				if ((this._POSISI_PPE != value))
				{
					this.OnPOSISI_PPEChanging(value);
					this.SendPropertyChanging();
					this._POSISI_PPE = value;
					this.SendPropertyChanged("POSISI_PPE");
					this.OnPOSISI_PPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(50)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this.OnCREATED_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY = value;
					this.SendPropertyChanged("CREATED_BY");
					this.OnCREATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_POS_BY", DbType="VarChar(50)")]
		public string CREATED_POS_BY
		{
			get
			{
				return this._CREATED_POS_BY;
			}
			set
			{
				if ((this._CREATED_POS_BY != value))
				{
					this.OnCREATED_POS_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATED_POS_BY = value;
					this.SendPropertyChanged("CREATED_POS_BY");
					this.OnCREATED_POS_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> UPDATED_DATE
		{
			get
			{
				return this._UPDATED_DATE;
			}
			set
			{
				if ((this._UPDATED_DATE != value))
				{
					this.OnUPDATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_DATE = value;
					this.SendPropertyChanged("UPDATED_DATE");
					this.OnUPDATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="VarChar(50)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this.OnUPDATED_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATED_BY = value;
					this.SendPropertyChanged("UPDATED_BY");
					this.OnUPDATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(MAX)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this.OnREMARKSChanging(value);
					this.SendPropertyChanging();
					this._REMARKS = value;
					this.SendPropertyChanged("REMARKS");
					this.OnREMARKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATH_ATTACHMENT", DbType="VarChar(200)")]
		public string PATH_ATTACHMENT
		{
			get
			{
				return this._PATH_ATTACHMENT;
			}
			set
			{
				if ((this._PATH_ATTACHMENT != value))
				{
					this.OnPATH_ATTACHMENTChanging(value);
					this.SendPropertyChanging();
					this._PATH_ATTACHMENT = value;
					this.SendPropertyChanged("PATH_ATTACHMENT");
					this.OnPATH_ATTACHMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_FORM_CAAB", DbType="VarChar(200)")]
		public string UPLOAD_FORM_CAAB
		{
			get
			{
				return this._UPLOAD_FORM_CAAB;
			}
			set
			{
				if ((this._UPLOAD_FORM_CAAB != value))
				{
					this.OnUPLOAD_FORM_CAABChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_FORM_CAAB = value;
					this.SendPropertyChanged("UPLOAD_FORM_CAAB");
					this.OnUPLOAD_FORM_CAABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_SH", DbType="VarChar(100)")]
		public string URL_FORM_SH
		{
			get
			{
				return this._URL_FORM_SH;
			}
			set
			{
				if ((this._URL_FORM_SH != value))
				{
					this.OnURL_FORM_SHChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_SH = value;
					this.SendPropertyChanged("URL_FORM_SH");
					this.OnURL_FORM_SHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_PLNTMNGR", DbType="VarChar(100)")]
		public string URL_FORM_PLNTMNGR
		{
			get
			{
				return this._URL_FORM_PLNTMNGR;
			}
			set
			{
				if ((this._URL_FORM_PLNTMNGR != value))
				{
					this.OnURL_FORM_PLNTMNGRChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_PLNTMNGR = value;
					this.SendPropertyChanged("URL_FORM_PLNTMNGR");
					this.OnURL_FORM_PLNTMNGRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_PLNTDH", DbType="VarChar(100)")]
		public string URL_FORM_PLNTDH
		{
			get
			{
				return this._URL_FORM_PLNTDH;
			}
			set
			{
				if ((this._URL_FORM_PLNTDH != value))
				{
					this.OnURL_FORM_PLNTDHChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_PLNTDH = value;
					this.SendPropertyChanged("URL_FORM_PLNTDH");
					this.OnURL_FORM_PLNTDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_PM_PENGIRIM", DbType="VarChar(100)")]
		public string URL_FORM_PM_PENGIRIM
		{
			get
			{
				return this._URL_FORM_PM_PENGIRIM;
			}
			set
			{
				if ((this._URL_FORM_PM_PENGIRIM != value))
				{
					this.OnURL_FORM_PM_PENGIRIMChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_PM_PENGIRIM = value;
					this.SendPropertyChanged("URL_FORM_PM_PENGIRIM");
					this.OnURL_FORM_PM_PENGIRIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_PM_PENERIMA", DbType="VarChar(100)")]
		public string URL_FORM_PM_PENERIMA
		{
			get
			{
				return this._URL_FORM_PM_PENERIMA;
			}
			set
			{
				if ((this._URL_FORM_PM_PENERIMA != value))
				{
					this.OnURL_FORM_PM_PENERIMAChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_PM_PENERIMA = value;
					this.SendPropertyChanged("URL_FORM_PM_PENERIMA");
					this.OnURL_FORM_PM_PENERIMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_DIVHEAD_ENG", DbType="VarChar(100)")]
		public string URL_FORM_DIVHEAD_ENG
		{
			get
			{
				return this._URL_FORM_DIVHEAD_ENG;
			}
			set
			{
				if ((this._URL_FORM_DIVHEAD_ENG != value))
				{
					this.OnURL_FORM_DIVHEAD_ENGChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_DIVHEAD_ENG = value;
					this.SendPropertyChanged("URL_FORM_DIVHEAD_ENG");
					this.OnURL_FORM_DIVHEAD_ENGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_DIVHEAD_OPR", DbType="VarChar(100)")]
		public string URL_FORM_DIVHEAD_OPR
		{
			get
			{
				return this._URL_FORM_DIVHEAD_OPR;
			}
			set
			{
				if ((this._URL_FORM_DIVHEAD_OPR != value))
				{
					this.OnURL_FORM_DIVHEAD_OPRChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_DIVHEAD_OPR = value;
					this.SendPropertyChanged("URL_FORM_DIVHEAD_OPR");
					this.OnURL_FORM_DIVHEAD_OPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL_FORM_DONE", DbType="VarChar(100)")]
		public string URL_FORM_DONE
		{
			get
			{
				return this._URL_FORM_DONE;
			}
			set
			{
				if ((this._URL_FORM_DONE != value))
				{
					this.OnURL_FORM_DONEChanging(value);
					this.SendPropertyChanging();
					this._URL_FORM_DONE = value;
					this.SendPropertyChanged("URL_FORM_DONE");
					this.OnURL_FORM_DONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIVED_SM", DbType="Date")]
		public System.Nullable<System.DateTime> DATE_RECEIVED_SM
		{
			get
			{
				return this._DATE_RECEIVED_SM;
			}
			set
			{
				if ((this._DATE_RECEIVED_SM != value))
				{
					this.OnDATE_RECEIVED_SMChanging(value);
					this.SendPropertyChanging();
					this._DATE_RECEIVED_SM = value;
					this.SendPropertyChanged("DATE_RECEIVED_SM");
					this.OnDATE_RECEIVED_SMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BERITA_ACARA_SM", DbType="VarChar(MAX)")]
		public string BERITA_ACARA_SM
		{
			get
			{
				return this._BERITA_ACARA_SM;
			}
			set
			{
				if ((this._BERITA_ACARA_SM != value))
				{
					this.OnBERITA_ACARA_SMChanging(value);
					this.SendPropertyChanging();
					this._BERITA_ACARA_SM = value;
					this.SendPropertyChanged("BERITA_ACARA_SM");
					this.OnBERITA_ACARA_SMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG_REMARKS", DbType="VarChar(MAX)")]
		public string FLAG_REMARKS
		{
			get
			{
				return this._FLAG_REMARKS;
			}
			set
			{
				if ((this._FLAG_REMARKS != value))
				{
					this.OnFLAG_REMARKSChanging(value);
					this.SendPropertyChanging();
					this._FLAG_REMARKS = value;
					this.SendPropertyChanged("FLAG_REMARKS");
					this.OnFLAG_REMARKSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
