#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSO687_CONSOLEAPP.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_MANAGEMENT_SERVICES_KPT")]
	public partial class DB_MNGMT_SRVCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_UPLOAD_JOB_MASTER(TBL_T_UPLOAD_JOB_MASTER instance);
    partial void UpdateTBL_T_UPLOAD_JOB_MASTER(TBL_T_UPLOAD_JOB_MASTER instance);
    partial void DeleteTBL_T_UPLOAD_JOB_MASTER(TBL_T_UPLOAD_JOB_MASTER instance);
    #endregion
		
		public DB_MNGMT_SRVCDataContext() : 
				base(global::MSO687_CONSOLEAPP.Properties.Settings.Default.DB_MANAGEMENT_SERVICES_KPTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MNGMT_SRVCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MNGMT_SRVCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MNGMT_SRVCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_MNGMT_SRVCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_T_UPLOAD_JOB_MASTER> TBL_T_UPLOAD_JOB_MASTERs
		{
			get
			{
				return this.GetTable<TBL_T_UPLOAD_JOB_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_UPLOAD_JOB_MASTER")]
	public partial class TBL_T_UPLOAD_JOB_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _JOB_ID;
		
		private string _SERVER_ID;
		
		private string _SCRIPT_CODE;
		
		private string _ELLIPSE_USERNAME;
		
		private string _ELLIPSE_PASSWORD;
		
		private string _ELLIPSE_POSITION;
		
		private string _ELLIPSE_DISTRICT;
		
		private System.Nullable<System.DateTime> _POST_DATETIME;
		
		private System.Nullable<System.DateTime> _RUN_DATETIME;
		
		private System.Nullable<System.DateTime> _FINISH_DATETIME;
		
		private System.Nullable<int> _JOB_STATUS;
		
		private string _JOB_REMARK;
		
		private string _DB_SERVER_NAME;
		
		private string _DATABASE_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJOB_IDChanging(string value);
    partial void OnJOB_IDChanged();
    partial void OnSERVER_IDChanging(string value);
    partial void OnSERVER_IDChanged();
    partial void OnSCRIPT_CODEChanging(string value);
    partial void OnSCRIPT_CODEChanged();
    partial void OnELLIPSE_USERNAMEChanging(string value);
    partial void OnELLIPSE_USERNAMEChanged();
    partial void OnELLIPSE_PASSWORDChanging(string value);
    partial void OnELLIPSE_PASSWORDChanged();
    partial void OnELLIPSE_POSITIONChanging(string value);
    partial void OnELLIPSE_POSITIONChanged();
    partial void OnELLIPSE_DISTRICTChanging(string value);
    partial void OnELLIPSE_DISTRICTChanged();
    partial void OnPOST_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnPOST_DATETIMEChanged();
    partial void OnRUN_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnRUN_DATETIMEChanged();
    partial void OnFINISH_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnFINISH_DATETIMEChanged();
    partial void OnJOB_STATUSChanging(System.Nullable<int> value);
    partial void OnJOB_STATUSChanged();
    partial void OnJOB_REMARKChanging(string value);
    partial void OnJOB_REMARKChanged();
    partial void OnDB_SERVER_NAMEChanging(string value);
    partial void OnDB_SERVER_NAMEChanged();
    partial void OnDATABASE_NAMEChanging(string value);
    partial void OnDATABASE_NAMEChanged();
    #endregion
		
		public TBL_T_UPLOAD_JOB_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_ID", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string JOB_ID
		{
			get
			{
				return this._JOB_ID;
			}
			set
			{
				if ((this._JOB_ID != value))
				{
					this.OnJOB_IDChanging(value);
					this.SendPropertyChanging();
					this._JOB_ID = value;
					this.SendPropertyChanged("JOB_ID");
					this.OnJOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_ID", DbType="VarChar(100)")]
		public string SERVER_ID
		{
			get
			{
				return this._SERVER_ID;
			}
			set
			{
				if ((this._SERVER_ID != value))
				{
					this.OnSERVER_IDChanging(value);
					this.SendPropertyChanging();
					this._SERVER_ID = value;
					this.SendPropertyChanged("SERVER_ID");
					this.OnSERVER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRIPT_CODE", DbType="VarChar(100)")]
		public string SCRIPT_CODE
		{
			get
			{
				return this._SCRIPT_CODE;
			}
			set
			{
				if ((this._SCRIPT_CODE != value))
				{
					this.OnSCRIPT_CODEChanging(value);
					this.SendPropertyChanging();
					this._SCRIPT_CODE = value;
					this.SendPropertyChanged("SCRIPT_CODE");
					this.OnSCRIPT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELLIPSE_USERNAME", DbType="VarChar(50)")]
		public string ELLIPSE_USERNAME
		{
			get
			{
				return this._ELLIPSE_USERNAME;
			}
			set
			{
				if ((this._ELLIPSE_USERNAME != value))
				{
					this.OnELLIPSE_USERNAMEChanging(value);
					this.SendPropertyChanging();
					this._ELLIPSE_USERNAME = value;
					this.SendPropertyChanged("ELLIPSE_USERNAME");
					this.OnELLIPSE_USERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELLIPSE_PASSWORD", DbType="VarChar(50)")]
		public string ELLIPSE_PASSWORD
		{
			get
			{
				return this._ELLIPSE_PASSWORD;
			}
			set
			{
				if ((this._ELLIPSE_PASSWORD != value))
				{
					this.OnELLIPSE_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._ELLIPSE_PASSWORD = value;
					this.SendPropertyChanged("ELLIPSE_PASSWORD");
					this.OnELLIPSE_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELLIPSE_POSITION", DbType="VarChar(50)")]
		public string ELLIPSE_POSITION
		{
			get
			{
				return this._ELLIPSE_POSITION;
			}
			set
			{
				if ((this._ELLIPSE_POSITION != value))
				{
					this.OnELLIPSE_POSITIONChanging(value);
					this.SendPropertyChanging();
					this._ELLIPSE_POSITION = value;
					this.SendPropertyChanged("ELLIPSE_POSITION");
					this.OnELLIPSE_POSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELLIPSE_DISTRICT", DbType="VarChar(50)")]
		public string ELLIPSE_DISTRICT
		{
			get
			{
				return this._ELLIPSE_DISTRICT;
			}
			set
			{
				if ((this._ELLIPSE_DISTRICT != value))
				{
					this.OnELLIPSE_DISTRICTChanging(value);
					this.SendPropertyChanging();
					this._ELLIPSE_DISTRICT = value;
					this.SendPropertyChanged("ELLIPSE_DISTRICT");
					this.OnELLIPSE_DISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POST_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> POST_DATETIME
		{
			get
			{
				return this._POST_DATETIME;
			}
			set
			{
				if ((this._POST_DATETIME != value))
				{
					this.OnPOST_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._POST_DATETIME = value;
					this.SendPropertyChanged("POST_DATETIME");
					this.OnPOST_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUN_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> RUN_DATETIME
		{
			get
			{
				return this._RUN_DATETIME;
			}
			set
			{
				if ((this._RUN_DATETIME != value))
				{
					this.OnRUN_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._RUN_DATETIME = value;
					this.SendPropertyChanged("RUN_DATETIME");
					this.OnRUN_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> FINISH_DATETIME
		{
			get
			{
				return this._FINISH_DATETIME;
			}
			set
			{
				if ((this._FINISH_DATETIME != value))
				{
					this.OnFINISH_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._FINISH_DATETIME = value;
					this.SendPropertyChanged("FINISH_DATETIME");
					this.OnFINISH_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_STATUS", DbType="Int")]
		public System.Nullable<int> JOB_STATUS
		{
			get
			{
				return this._JOB_STATUS;
			}
			set
			{
				if ((this._JOB_STATUS != value))
				{
					this.OnJOB_STATUSChanging(value);
					this.SendPropertyChanging();
					this._JOB_STATUS = value;
					this.SendPropertyChanged("JOB_STATUS");
					this.OnJOB_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_REMARK", DbType="VarChar(MAX)")]
		public string JOB_REMARK
		{
			get
			{
				return this._JOB_REMARK;
			}
			set
			{
				if ((this._JOB_REMARK != value))
				{
					this.OnJOB_REMARKChanging(value);
					this.SendPropertyChanging();
					this._JOB_REMARK = value;
					this.SendPropertyChanged("JOB_REMARK");
					this.OnJOB_REMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_SERVER_NAME", DbType="VarChar(100)")]
		public string DB_SERVER_NAME
		{
			get
			{
				return this._DB_SERVER_NAME;
			}
			set
			{
				if ((this._DB_SERVER_NAME != value))
				{
					this.OnDB_SERVER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DB_SERVER_NAME = value;
					this.SendPropertyChanged("DB_SERVER_NAME");
					this.OnDB_SERVER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATABASE_NAME", DbType="VarChar(100)")]
		public string DATABASE_NAME
		{
			get
			{
				return this._DATABASE_NAME;
			}
			set
			{
				if ((this._DATABASE_NAME != value))
				{
					this.OnDATABASE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DATABASE_NAME = value;
					this.SendPropertyChanged("DATABASE_NAME");
					this.OnDATABASE_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
