<?xml version="1.0" encoding="utf-8"?><Database Name="DB_PLANT_PPE_NEW_KPT" Class="DB_PLANT_PPE_CONSOLEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=kphosq101\shpol;Initial Catalog=DB_PLANT_PPE_NEW_KPT;User ID=sqlservices" SettingsObjectName="MSO687_CONSOLEAPP.Properties.Settings" SettingsPropertyName="DB_PLANT_PPE_NEW_KPTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VW_MSF685" Member="VW_MSF685s">
    <Type Name="VW_MSF685">
      <Column Name="ASSET_NO" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="ASSET_TY" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="SUB_ASSET_NO" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="ACCT_PROFILE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="ASSET_CLASSIF" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="CAPITAL_TYPE" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CASH_GEN_UNIT" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="CREATION_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="CREATION_TIME" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="CREATION_USER" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DEPR_EXP_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="DEPR_IND" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX1" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX2" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX3" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX4" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX5" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX6" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX7" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DESC_CODEX8" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_TIME" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_USER" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAA_CODE" Type="System.String" DbType="Char(24) NOT NULL" CanBeNull="false" />
      <Column Name="REPORT_CODE" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="RETIREMENT_CODE" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="RETIREMENT_DETL" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="REVAL_SUB_CLASS" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="REVIEWED_STATUS" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="SUB_ASSET_DESC" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="SUB_ASSET_STATUS" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="TRACK_NUMBER" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="TRACK_TYPE" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="VINTAGE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_MOD_EMP" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_ACCT_PROFILE" Member="VW_R_ACCT_PROFILEs">
    <Type Name="VW_R_ACCT_PROFILE">
      <Column Name="EQUIP_NO" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="EQUIP_LOCATION" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="SUB_ASSET_NO" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="ACCT_PROFILE" Type="System.String" DbType="Char(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_PPE" Member="TBL_T_PPEs">
    <Type Name="TBL_T_PPE">
      <Column Name="ID_PPE" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="APPROVAL_ORDER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PPE_NO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DISTRICT_FROM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DISTRICT_TO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOC_FROM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOC_TO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EQUIP_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EGI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EQUIP_CLASS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SERIAL_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PPE_DESC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="POSISI_PPE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_POS_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PATH_ATTACHMENT" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UPLOAD_FORM_CAAB" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="URL_FORM_SH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PLNTMNGR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PLNTDH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PM_PENGIRIM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PM_PENERIMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_DIVHEAD_ENG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_DIVHEAD_OPR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_DONE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DATE_RECEIVED_SM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BERITA_ACARA_SM" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FLAG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_T_MSF687_TRASNFER_ASSET" Member="VW_T_MSF687_TRASNFER_ASSETs">
    <Type Name="VW_T_MSF687_TRASNFER_ASSET">
      <Column Name="JOB_MASTER_ID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PPE" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="APPROVAL_ORDER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PPE_NO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DISTRICT_FROM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DISTRICT_TO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOC_FROM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOC_TO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EQUIP_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EGI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EQUIP_CLASS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SERIAL_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PPE_DESC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="POSISI_PPE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_POS_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PATH_ATTACHMENT" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UPLOAD_FORM_CAAB" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="URL_FORM_SH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PLNTMNGR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PLNTDH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PM_PENGIRIM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_PM_PENERIMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_DIVHEAD_ENG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_DIVHEAD_OPR" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="URL_FORM_DONE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DATE_RECEIVED_SM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BERITA_ACARA_SM" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FLAG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>